# .goreleaser.yml

builds:
  - id: "thola"

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    main: ./main.go
    binary: thola

    env:
      - CGO_ENABLED=0

  - id: "thola-client"

    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm64

    main: ./main.go
    binary: thola-client

    flags:
      - -tags=client
    env:
      - CGO_ENABLED=0

nfpms:
  - id: "thola"
    homepage: https://thola.io
    maintainer: team@thola.io
    description: Network Monitoring Tool
    license: BSD-2-clause
    formats:
      - deb
    contents:
      - src: scripts/thola.service
        dst: /lib/systemd/system/thola.service
    scripts:
      preinstall: "scripts/pre-install.sh"
      postinstall: "scripts/post-install.sh"
      postremove: "scripts/post-uninstall.sh"

archives:
  - builds:
      - thola
      - thola-client
