name: "XG"

match:
  logical_operator: OR
  conditions:
    - type: SysObjectID
      match_mode: startsWith
      values:
        - .1.3.6.1.4.1.2604.5

components:
  interfaces:
    properties:
      detection: snmpwalk
      values:
        ethernet_like:
          ignore: true
