name: logpoint

match:
  conditions:
    - type: snmpget
      oid: .1.3.6.1.4.1.54322.1.6
      match_mode: regex
      values:
        - '.*'
  logical_operator: OR

config:
  components:
    siem: true

components:
  siem:
    siem:
      - detection: constant
        value: "LogPoint"
    last_recorded_messages_per_second_normalizer:
      - detection: snmpget
        oid: .1.3.6.1.4.1.54322.1.1
    average_messages_per_second_last_5_min_normalizer:
      - detection: snmpget
        oid: .1.3.6.1.4.1.54322.1.2
    last_recorded_messages_per_second_store_handler:
      - detection: snmpget
        oid: .1.3.6.1.4.1.54322.1.3
    average_messages_per_second_last_5_min_store_handler:
      - detection: snmpget
        oid: .1.3.6.1.4.1.54322.1.4
    services_currently_down:
      - detection: snmpget
        oid: .1.3.6.1.4.1.54322.1.5
    system_version:
      - detection: snmpget
        oid: .1.3.6.1.4.1.54322.1.6
