name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build main
      run: go build -v .

    - name: Build client
      run: go build -tags client -v .